version: '3.8'

services:
  child-project:
    build:
      context: .
      dockerfile: Dockerfile
    image: child-project:latest
    container_name: child-project
    restart: always
    networks:
      - coolify
    expose:
      - "3000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://user.3bdulrahman.com
      - ASSET_URL=https://user.3bdulrahman.com
      - FORCE_HTTPS=true
      - PARENT_URL=https://admin.3bdulrahman.com

networks:
  coolify:
    external: true
